# Generated by Django 3.0.6 on 2020-05-27 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadreport', '0002_auto_20200527_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.IntegerField(default=123123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='hours_worked',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='job_group',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
