# Generated by Django 3.0.6 on 2020-05-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadreport', '0003_auto_20200527_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.CharField(max_length=20),
        ),
    ]
