# Generated by Django 3.0.6 on 2020-05-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadreport', '0004_auto_20200527_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('hours_worked', models.FloatField()),
                ('employee_id', models.IntegerField()),
                ('job_group', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
